#Model Library

# the type of dynamic content
type: "shotgun_entity"

# the ShotGrid field to use for the folder name
name: "code"

# the ShotGrid entity type to connect to
entity_type: "Episode"

# ShotGrid filters to apply when getting the list of items
# this should be a list of dicts, each dict containing 
# three fields: path, relation and values
# (this is std ShotGrid API syntax)
# any values starting with $ are resolved into path objects
filters: [ { "path": "project", "relation": "is", "values": [ "$model_library" ] } ]