# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Apps and engines loaded when an customentity02 is loaded. Since std VFX
  config template has a file system structure which is centered around pipeline
  steps, this environment is largely empty. Most of the work takes place on a
  level in the file system where both an customentity02 and a pipeline step is available
  - e.g customentity02 Hero, modeling, so all apps for loading, publishing etc. are
  located in the customentity02_step environment. This environment mostly contains
  utility apps and the tank work files app, which lets you choose a task to work
  on and load associated content into an application.

################################################################################

includes:
- ./includes/frameworks.yml
- ./includes/settings/tk-3dsmaxplus.yml
- ./includes/settings/tk-3dsmax.yml
- ./includes/settings/tk-houdini.yml
- ./includes/settings/tk-mari.yml
- ./includes/settings/tk-maya.yml
- ./includes/settings/tk-motionbuilder.yml
- ./includes/settings/tk-nuke.yml
- ./includes/settings/tk-photoshopcc.yml
- ./includes/settings/tk-aftereffects.yml
- ./includes/settings/tk-alias.yml
- ./includes/settings/tk-vred.yml
- ./includes/settings/tk-shell.yml
- ./includes/settings/tk-shotgun.yml

################################################################################
# configuration for all engines to load in an customentity02 context

engines:
  tk-3dsmaxplus: "@settings.tk-3dsmaxplus.customentity02"
  tk-3dsmax: "@settings.tk-3dsmax.customentity02"
  tk-houdini: "@settings.tk-houdini.customentity02"
  tk-mari: "@settings.tk-mari.customentity02"
  tk-maya: "@settings.tk-maya.customentity02"
  tk-motionbuilder: "@settings.tk-motionbuilder.customentity02"
  tk-nuke: "@settings.tk-nuke.customentity02"
  tk-photoshopcc: "@settings.tk-photoshopcc.customentity02"
  tk-aftereffects: "@settings.tk-aftereffects.customentity02"
  tk-alias: "@settings.tk-alias.customentity02"
  tk-vred: "@settings.tk-vred.customentity02"
  tk-shell: "@settings.tk-shell.customentity02"
  tk-shotgun: "@settings.tk-shotgun.customentity02"

################################################################################
# reference all of the common frameworks

frameworks: "@frameworks"
