# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

################################################################################

includes:
- ../app_locations.yml
- ../engine_locations.yml
- ./tk-multi-loader2.yml
- ./tk-multi-publish2.yml
- ./tk-multi-screeningroom.yml
- ./tk-multi-shotgunpanel.yml
- ./tk-multi-snapshot.yml
- ./tk-multi-workfiles2.yml
- ./tk-multi-setframerange.yml
- ./tk-multi-breakdown2.yml

################################################################################

# asset
settings.tk-3dsmax.asset:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-pythonconsole:
      location: "@apps.tk-multi-pythonconsole.location"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.3dsmax"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  location: "@engines.tk-3dsmax.location"

# material
settings.tk-3dsmax.material:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-pythonconsole:
      location: "@apps.tk-multi-pythonconsole.location"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.3dsmax"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  location: "@engines.tk-3dsmax.location"
  
  # material_step 
settings.tk-3dsmax.material_step:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-breakdown:
      display_name: "Legacy Breakdown"
      location: "@apps.tk-multi-breakdown.location"
    tk-multi-breakdown2: "@settings.tk-multi-breakdown2.3dsmax"
    tk-multi-loader2: "@settings.tk-multi-loader2.3dsmax"
    tk-multi-publish2: "@settings.tk-multi-publish2.3dsmax.material_step"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.3dsmax"
    tk-multi-snapshot: "@settings.tk-multi-snapshot.3dsmax.material_step"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.3dsmax.material_step"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-snapshot, name: Snapshot...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  - {app_instance: tk-multi-publish2, name: Publish...}
  - {app_instance: tk-multi-breakdown2, name: Scene Breakdown...}
  template_project: asset_work_area_max_material
  location: "@engines.tk-3dsmax.location"

  # scene
settings.tk-3dsmax.customentity02:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-pythonconsole:
      location: "@apps.tk-multi-pythonconsole.location"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.3dsmax"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  location: "@engines.tk-3dsmax.location"

# asset_step 
settings.tk-3dsmax.asset_step:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-breakdown:
      display_name: "Legacy Breakdown"
      location: "@apps.tk-multi-breakdown.location"
    tk-multi-breakdown2: "@settings.tk-multi-breakdown2.3dsmax"
    tk-multi-loader2: "@settings.tk-multi-loader2.3dsmax"
    tk-multi-publish2: "@settings.tk-multi-publish2.3dsmax.asset_step-model"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.3dsmax"
    tk-multi-snapshot: "@settings.tk-multi-snapshot.3dsmax.asset_step-model"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.3dsmax.asset_step-model"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-snapshot, name: Snapshot...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  - {app_instance: tk-multi-publish2, name: Publish...}
  - {app_instance: tk-multi-breakdown2, name: Scene Breakdown...}
  template_project: asset_work_area_max_model
  location: "@engines.tk-3dsmax.location"


# # asset_step Model
# settings.tk-3dsmax.asset_step-model:
#   apps:
#     tk-multi-about:
#      location: "@apps.tk-multi-about.location"
#     tk-multi-breakdown:
#       display_name: "Legacy Breakdown"
#       location: "@apps.tk-multi-breakdown.location"
#     tk-multi-breakdown2: "@settings.tk-multi-breakdown2.3dsmax"
#     tk-multi-loader2: "@settings.tk-multi-loader2.3dsmax"
#     tk-multi-publish2: "@settings.tk-multi-publish2.3dsmax.asset_step-model"
#     tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
#     tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.3dsmax"
#     tk-multi-snapshot: "@settings.tk-multi-snapshot.3dsmax.asset_step-model"
#     tk-multi-workfiles2: "@settings.tk-multi-workfiles2.3dsmax.asset_step-model"
#     tk-multi-reviewsubmission: "@settings.tk-multi-reviewsubmission.3dsmax"
#   menu_favourites:
#   - {app_instance: tk-multi-workfiles2, name: File Open...}
#   - {app_instance: tk-multi-snapshot, name: Snapshot...}
#   - {app_instance: tk-multi-workfiles2, name: File Save...}
#   - {app_instance: tk-multi-publish2, name: Publish...}
#   - {app_instance: tk-multi-breakdown2, name: Scene Breakdown...}
#   template_project: asset_work_area_max_model
#   location: "@engines.tk-3dsmax.location"


# project
settings.tk-3dsmax.project:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-pythonconsole:
      location: "@apps.tk-multi-pythonconsole.location"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.3dsmax"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  location: "@engines.tk-3dsmax.location"

# sequence
settings.tk-3dsmax.sequence:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-pythonconsole:
      location: "@apps.tk-multi-pythonconsole.location"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.3dsmax"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  location: "@engines.tk-3dsmax.location"

# shot
settings.tk-3dsmax.shot:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-pythonconsole:
      location: "@apps.tk-multi-pythonconsole.location"
    tk-multi-setframerange: "@settings.tk-multi-setframerange.3dsmax"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.3dsmax"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  location: "@engines.tk-3dsmax.location"

# shot_step
settings.tk-3dsmax.shot_step:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-pythonconsole:
      location: "@apps.tk-multi-pythonconsole.location"
    tk-multi-setframerange: "@settings.tk-multi-setframerange.3dsmax"
    tk-multi-loader2: "@settings.tk-multi-loader2.3dsmax"
    tk-multi-publish2: "@settings.tk-multi-publish2.3dsmax.shot_step"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.3dsmax"
    tk-multi-snapshot: "@settings.tk-multi-snapshot.3dsmax.shot_step"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.3dsmax.shot_step"
  location: "@engines.tk-3dsmax.location"
